### ISSUE TITLE
Text Needing more info

### ISSUE THREAD

**Issue by ClementLagasse** [ARCADE-TEK-2026/archi_arcade#108]
IText should contains  :

 - Int Size -> so the graphics library are capable to show if a text is bigger than another 
 - std::string font_path -> so the graphics library knows which font to load into the GraphModule

**Comment by Saverio976** [comment]
le font path existe déjà

**Comment by Saverio976** [comment]
et, je trouve que implémenter une taille pour le text ça
- met en porte à feu la ncurse
- rajoute un truc chiant à faire dans l'impémentation
