### ISSUE TITLE
iRenderComp n'a pas de getType

### ISSUE THREAD

**Issue by Saverio976** [ARCADE-TEK-2026/archi_arcade#3]
Il faudrait un getType à IRenderComp pour différencier le IText du ISprite du IMusic

Qui veut faire la PR ?

**Comment by Saverio976** [comment]
![Screenshot_2023-03-15-21-32-52-51_99c04817c0de5652397fc8b56c3b3817.jpg](https://user-images.githubusercontent.com/57769503/225435390-118f98be-dc70-4e7b-8589-e95b7289d09a.jpg)

**Comment by guillaumeAbel** [comment]
Fix in actual xavier's branch, waiting for PR
