### ISSUE TITLE
getSystems() des libs graphiques doit retourner un shared_ptr, pas un unique_ptr

### ISSUE THREAD

**Issue by raphaelMrci** [ARCADE-TEK-2026/archi_arcade#48]
Le problème que nous rencontrons, c'est que partager des unique_ptr, ça demande soit de copier, soit de move le unique_ptr stocké dans la lib graphique.

Il serait plus judicieux d'utiliser des shared_ptr

```cpp
/**
 * @brief The game shared lib main entry point to get scenes
*
 * @return A unique_ptr on ISceneManager instance
*
* All game shared lib must have this function
 *
*/
std::unique_ptr<Arcade::Game::ISceneManager> getScenes();
```
à remplacer par

```cpp
/**
 * @brief The game shared lib main entry point to get scenes
*
 * @return A shared_ptr on ISceneManager instance
*
* All game shared lib must have this function
 *
*/
std::shared_ptr<Arcade::Game::ISceneManager> getScenes();
```

**Comment by raphaelMrci** [comment]
(Dans Api.hpp)

**Comment by Saverio976** [comment]
pourquoi tu veux stocker dans plusieurs variables c'est trucs ?

**Comment by raphaelMrci** [comment]
> pourquoi tu veux stocker dans plusieurs variables ces trucs ?

AAhhhhhhh, ok, donc l'idée, c'est de copier à chaque fois l'unique_ptr par le core, pour créer une nouvelle instance du jeu, avec les systems posées par défaut ?

Parce que si je récupère l'unique_ptr directement, je le supprime de l'instance de ma lib (`std::move()`). Mais il me faudrait plutôt créer un nouveau unique_ptr à chaque fois que je veux getSystems ?

**Comment by Saverio976** [comment]
Si tu as besoin de plus d'info, ou de comment on a l'idée de l'implémenter, on peut passer par vocal ?
