### ISSUE TITLE
Plus d'ajouts

### ISSUE THREAD

**Issue by GlassAlo** [ARCADE-TEK-2026/archi_arcade#8]
IEntity -> removeComponent(compType) = enlever component plus utile pour l'entité
IEntityManager & IEventManager -> clearAllEntity/Events = remove tout les entities/events stockés
namespace components = IComponents & fils
namespace systems = ISystems & fils

**Comment by Saverio976** [comment]
dans quel cas c'est intérressant de remove tous les component de CompType ?
(par contre pouvoir remove un component oui xD, l'oubli de fou xD)

**Comment by GlassAlo** [comment]
Parce que tu veux pas écrire "moveSystem" "drawSystem" "positionComponent"

**Comment by Saverio976** [comment]
ça veut dire j'enlève le namespace Game par ce que y a que 1 system dedans, et le systeme GameLogic va dans le namespace System

**Comment by GlassAlo** [comment]
Pour moi gameLogic devrait pas faire partie de l'archi donc bon
Pareil pour IGraph

**Comment by Saverio976** [comment]
pour moi, c'est justement dans un soucis de clarté pour l'UML

un utilisateur de la lib va dériver ses systems de IGraph si il fait un system plutôt graphique, et IGameLogic si il fait un system plutôt grame

**Comment by GlassAlo** [comment]
C'est rajouter une interface pour rien, mes systems vont pas hériter d'un truc qui ajoute rien jsp

**Comment by Saverio976** [comment]
ça veut dire ton UML va avoir tous dans namespace System

**Comment by GlassAlo** [comment]
Tous les systems oui

**Comment by Saverio976** [comment]
j'ai peut être mal compris

ce que tu veux faire c'est coder les cpp system du jeu dans le namespace System ?

**Comment by GlassAlo** [comment]
Ce que je veux c'est que mes systems héritent de ISytem, rajouter une couche qui n'ajoute rien pour les systèmes, c'est pas utile, le namespace sera là pour les contenir et enlever le préfixe ou suffixe. IGameLogic et IGraph sont juste des systems comme les autres imo

**Comment by Saverio976** [comment]
Je comprends toujours pas, tu peux faire un example d'utilisation ?

**Comment by GlassAlo** [comment]
CompType est pas une enum class la, c'est une struct, c'est pas normal, si ?

**Comment by Saverio976** [comment]
Non en effet, il y avait enum struct à un moment
